version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: CashFlow.API/Dockerfile
    ports:
      - "5047:80"
      - "7107:443"
    environment:
      DATABASE_NAME: dbcashflow
      DATABASE_USER: postgres
      DATABASE_PASS: 5dacb9130fb44377ad519eb2b479741f
      DATABASE_PORT: 5432
      DATABASE_HOST: dbpostgres
    depends_on:
      - "dbpostgres"
    restart: always
    networks:
      - cashflow_cashflownet

  dbpostgres:
    image: postgres:latest
    hostname: dbpostgres
    container_name: dbpostgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "5dacb9130fb44377ad519eb2b479741f"
      POSTGRES_DB: dbcashflow
    volumes:
      - type: bind
        source: C:\cashflow\postgresql\data
        target: /var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - cashflow_cashflownet

networks:
  cashflow_cashflownet:
    driver: bridge
